// HSH Cash Log - Type Definitions

export type UserRole = 'staff' | 'manager' | 'hk_staff';

export type PaymentMethod = 'Cash' | 'GCash' | 'Maya' | 'Bank';

export type FlowType = 'IN' | 'OUT' | 'TRANSFER';

export type RoomType = 'Casa Clara' | 'Casa Grande' | 'Casa Doble';

export type RoomStatus = 
  | 'Check in' 
  | 'Checkout' 
  | 'Ready' 
  | 'Cleaning' 
  | 'MUR' 
  | 'DND';

// Individual room definition
export interface Room {
  id: string;           // e.g., "CC-202"
  number: string;       // e.g., "202"
  roomType: RoomType;
  displayName: string;  // e.g., "R 202"
}

// All rooms in the hotel
export const ALL_ROOMS: Room[] = [
  // Casa Clara rooms
  { id: 'CC-202', number: '202', roomType: 'Casa Clara', displayName: 'R 202' },
  { id: 'CC-203', number: '203', roomType: 'Casa Clara', displayName: 'R 203' },
  { id: 'CC-204', number: '204', roomType: 'Casa Clara', displayName: 'R 204' },
  { id: 'CC-205', number: '205', roomType: 'Casa Clara', displayName: 'R 205' },
  { id: 'CC-302', number: '302', roomType: 'Casa Clara', displayName: 'R 302' },
  { id: 'CC-303', number: '303', roomType: 'Casa Clara', displayName: 'R 303' },
  { id: 'CC-304', number: '304', roomType: 'Casa Clara', displayName: 'R 304' },
  { id: 'CC-402', number: '402', roomType: 'Casa Clara', displayName: 'R 402' },
  { id: 'CC-403', number: '403', roomType: 'Casa Clara', displayName: 'R 403' },
  { id: 'CC-404', number: '404', roomType: 'Casa Clara', displayName: 'R 404' },
  // Casa Grande rooms
  { id: 'CG-206', number: '206', roomType: 'Casa Grande', displayName: 'R 206' },
  { id: 'CG-301', number: '301', roomType: 'Casa Grande', displayName: 'R 301' },
  { id: 'CG-401', number: '401', roomType: 'Casa Grande', displayName: 'R 401' },
  // Casa Doble rooms
  { id: 'CD-305', number: '305', roomType: 'Casa Doble', displayName: 'R 305' },
];

export type InflowCategory = 
  | 'Room Payment'
  | 'Room Payment w/ Security Dep'
  | 'Security Deposit'
  | 'Reservation DP'
  | 'Extension Fee'
  | 'Early Check-in Fee'
  | 'Late Check-out Fee'
  | 'Extra Guest Fee'
  | 'Charges'
  | 'Other Income';

export type OutflowCategory = 
  | 'Expense'
  | 'Refund'
  | 'Owner Withdrawal'
  | 'Cash Adjustment'
  | 'Sec Dep Cash Movement'  // Auto-generated by system
  | 'Other Cash Out';

export type TransferCategory = 'Transfer';

export type TransactionCategory = InflowCategory | OutflowCategory | TransferCategory;

export interface User {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  isActive: boolean;
}

export interface RoomBooking {
  roomType: RoomType;
  quantity: number;
  roomIds?: string[]; // Selected individual room IDs
}

export interface Transaction {
  id: string;
  date: string;
  time: string;
  timestamp: number;
  staffId: string;
  staffName: string;
  flowType: FlowType;
  category: TransactionCategory;
  amount: number;
  paymentMethod: PaymentMethod;
  transferTo?: PaymentMethod;
  guestName?: string;
  roomBookings?: RoomBooking[]; // Multi-room support
  notes: string;
  isReversal: boolean;
  originalTransactionId?: string;
  reversalReason?: string;
  runningBalance: number;
  // Room status update from this transaction
  roomStatusUpdate?: {
    status: RoomStatus;
    roomIds: string[]; // Individual room IDs to update
  };
  // Security deposit movement flag (excluded from revenue totals)
  isSecDepMovement?: boolean;
  // Manager edit tracking
  editedByManager?: boolean;
  editedAt?: string;
  // Void tracking (soft delete)
  isVoid?: boolean;
  voidedAt?: string;
}

export interface RoomState {
  roomId: string;       // Individual room ID
  roomType: RoomType;
  status: RoomStatus;
  lastUpdated: string;
  updatedBy: string;
  updatedById: string;
  notes?: string;
}

export interface DailySummary {
  date: string;
  openingCash: number;
  cashIn: number;
  cashOut: number;
  expectedEndingCash: number;
  gCashTotal: number;
  mayaTotal: number;
  bankTotal: number;
  transactionCount: number;
}

export interface CashCount {
  date: string;
  expectedCash: number;
  actualCash: number;
  difference: number;
  status: 'Balanced' | 'Short' | 'Over';
  countedBy: string;
  countedAt: string;
  notes?: string;
}

export const INFLOW_CATEGORIES: InflowCategory[] = [
  'Room Payment',
  'Room Payment w/ Security Dep',
  'Reservation DP',
  'Extension Fee',
  'Early Check-in Fee',
  'Late Check-out Fee',
  'Extra Guest Fee',
  'Charges',
  'Other Income'
];

export const OUTFLOW_CATEGORIES: OutflowCategory[] = [
  'Expense',
  'Refund',
  'Owner Withdrawal',
  'Cash Adjustment',
  'Sec Dep Cash Movement',
  'Other Cash Out'
];

export const TRANSFER_CATEGORY: TransferCategory = 'Transfer';

export const EXPENSE_SUBCATEGORIES = [
  'Utilities',
  'Supplies',
  'Maintenance',
  'Cleaning',
  'Food & Beverage',
  'Staff',
  'Marketing',
  'Other'
];

export const ROOM_TYPES: RoomType[] = [
  'Casa Clara',
  'Casa Grande',
  'Casa Doble'
];

export const ROOM_STATUSES: RoomStatus[] = [
  'Check in',
  'Checkout',
  'Ready',
  'Cleaning',
  'MUR',
  'DND'
];

// Categories that require Guest Name
export const CATEGORIES_REQUIRING_GUEST_NAME: string[] = [
  'Room Payment',
  'Room Payment w/ Security Dep',
  'Extension Fee',
  'Charges'
];

// Categories that require Room Bookings
export const CATEGORIES_REQUIRING_ROOMS: string[] = [
  'Room Payment',
  'Room Payment w/ Security Dep',
  'Extension Fee',
  'Charges'
];

// Categories that are booking-related (show guest fields optionally)
export const BOOKING_RELATED_CATEGORIES: string[] = [
  'Room Payment',
  'Room Payment w/ Security Dep',
  'Reservation DP',
  'Extension Fee',
  'Early Check-in Fee',
  'Late Check-out Fee',
  'Extra Guest Fee',
  'Refund'
];

// Status colors for UI (full card backgrounds)
export const ROOM_STATUS_COLORS: Record<RoomStatus, { bg: string; text: string; border: string; shadow: string }> = {
  'Check in': { bg: 'bg-green-500', text: 'text-white', border: 'border-green-600', shadow: 'shadow-green-200' },
  'Checkout': { bg: 'bg-red-500', text: 'text-white', border: 'border-red-600', shadow: 'shadow-red-200' },
  'Ready': { bg: 'bg-blue-500', text: 'text-white', border: 'border-blue-600', shadow: 'shadow-blue-200' },
  'Cleaning': { bg: 'bg-yellow-400', text: 'text-yellow-900', border: 'border-yellow-500', shadow: 'shadow-yellow-200' },
  'MUR': { bg: 'bg-purple-500', text: 'text-white', border: 'border-purple-600', shadow: 'shadow-purple-200' },
  'DND': { bg: 'bg-gray-500', text: 'text-white', border: 'border-gray-600', shadow: 'shadow-gray-200' }
};

// Status labels for display
export const ROOM_STATUS_LABELS: Record<RoomStatus, string> = {
  'Check in': 'Occupied',
  'Checkout': 'Dirty / Guest Left',
  'Ready': 'Clean & Available',
  'Cleaning': 'In Progress',
  'MUR': 'Make Up Room',
  'DND': 'Do Not Disturb'
};
